apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eshop-project
  namespace: argocd
spec:
  description: "Project for distributed microservices"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: eshop-dev
    - server: https://kubernetes.default.svc
      namespace: eshop-stage
    - server: https://kubernetes.default.svc
      namespace: eshop-prod
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: default
    - server: https://kubernetes.default.svc
      namespace: istio-system
    - server: https://kubernetes.default.svc
      namespace: ratelimit-system
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: argo-rollouts
    - server: https://kubernetes.default.svc
      namespace: external-secrets
  sourceRepos:
    - '*'  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
