<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Ordering.Application\Ordering.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\BuildingBlocks\BuildingBlocks.Messaging\Protos\Product.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
