global:
  namespace: ratelimit-system
  environment: dev
  ns: true
  domain: example.com
  projectName: eshop
hosts:
  hostApp: "{{ .Values.global.environment }}.{{ .Values.global.projectName }}.{{ .Values.global.domain }}"
  hostApi: "api.{{ .Values.global.environment }}.{{ .Values.global.projectName }}.{{ .Values.global.domain }}"
  hostId: "id.{{ .Values.global.environment }}.{{ .Values.global.projectName }}.{{ .Values.global.domain }}"