include:
  - local: '.gitlab/ci/stages.yml'
  - local: '.gitlab/ci/templates/security.yml'
  - local: '.gitlab/ci/templates/matrix.yml'
  - local: '.gitlab/ci/templates/docker.yml'
  - local: '.gitlab/ci/templates/sonar.yml'
  - local: '.gitlab/ci/templates/dotnet.yml'
  - local: '.gitlab/ci/templates/node.yml'
  - local: '.gitlab/ci/security.yml'
  - local: '.gitlab/ci/prepare.yml'
  - local: '.gitlab/ci/quality.yml'
  - local: '.gitlab/ci/docker.yml'
  - local: '.gitlab/ci/tests.yml'
  - template: Security/Secret-Detection.gitlab-ci.yml
