x-dotnet-common-env: &dotnet-common-env
    Kestrel__Endpoints__Http__Url: http://*:8080
    Kestrel__Endpoints__Https__Url: https://*:8081
    Kestrel__Endpoints__Https__Certificate__Path: /home/app/.aspnet/https/aspnetapp.pfx
    Kestrel__Endpoints__Https__Certificate__Password: devcert
    ASPNETCORE_HTTP_PORTS: "8080"
    ASPNETCORE_HTTPS_PORTS: "8081"
x-dotnet-common-volumes: &dotnet-common-volumes
    - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
    - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
    # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

services:
  catalogdb:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    ports:
      - 5400:5432
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - 5401:5432
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  # orderdb:
  #   container_name: orderdb
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Password@123
  #   ports:
  #     - 1433:1433
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql

  keycloak-db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@123
      POSTGRES_DB: keycloak
    ports:
      - 5402:5432
#    volumes:
#      - postgres_keycloak:/var/lib/postgresql/data/
  
  distributedcache:
    ports:
      - 6379:6379

  messagebroker:
    hostname: eshop-mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
  
  # discount.seq:
  #   container_name: Discount.Seq
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "5341:5341"
  #     - "80:80"
  
  keycloak.identity:
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: Password@123
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KK_TO_RMQ_URL: messagebroker
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: keycloak.exchange
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest
    depends_on:
      - keycloak-db
    command:
      - start-dev
      - --import-realm
    ports:
      - 8080:8080
    volumes:
      - ./keycloak-config/conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak-config/data/import/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak-config/providers/keycloak-to-rabbit-3.0.5.jar:/opt/keycloak/providers/keycloak-to-rabbit-3.0.5.jar

  catalog.api:
    environment:
      <<: *dotnet-common-env
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Server=catalogdb; Port=5432; Database=CatalogDb; User Id=postgres; Password=postgres; Include Error Detail=true
      MessageBroker__Host: amqp://messagebroker:5672
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
      Authentication__Authority: http://keycloak.identity:8080/realms/eshop
      Authentication__ValidIssuer: http://localhost:8080/realms/eshop
      Authentication__ClientId: eshop-client
      Authentication__Audience: eshop-client
    depends_on:
      - catalogdb
      - messagebroker
      - keycloak.identity
    ports:
      - 6000:8080
      - 6060:8081
    volumes: *dotnet-common-volumes

  basket.api:
    environment:
      <<: *dotnet-common-env
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Server=basketdb; Port=5432; Database=BasketDb; User Id=postgres; Password=postgres; Include Error Detail=true
      ConnectionStrings__Redis: distributedcache:6379
      MessageBroker__Host: amqp://messagebroker:5672
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
      Authentication__Authority: http://keycloak.identity:8080/realms/eshop
      Authentication__ValidIssuer: http://localhost:8080/realms/eshop
      Authentication__ClientId: eshop-client
      Authentication__Audience: eshop-client
      GrpcSettings__CatalogUrl: https://catalog.api:8081
      GrpcSettings__DiscountUrl: https://discount.grpc:8081
    depends_on:
      - basketdb
      - distributedcache
      - messagebroker
      - keycloak.identity
      - catalog.api
      # - discount.grpc
    ports:
      - 6001:8080
      - 6061:8081
    volumes: *dotnet-common-volumes

  # discount.grpc:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ConnectionStrings__Database=Data Source=discountdb.db
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=HTTP://discount.seq:5341/ingest/otlp/v1/traces
  #     - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

  #     - Kestrel__Endpoints__Http__Url=http://*:8080
  #     - Kestrel__Endpoints__Https__Url=https://*:8081
  #     - Kestrel__Endpoints__Https__Certificate__Path=/home/app/.aspnet/https/aspnetapp.pfx
  #     - Kestrel__Endpoints__Https__Certificate__Password=david
  #   ports:
  #     - "6002:8080"
  #     - "6062:8081"
  #   volumes:
  #     - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
  #     # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # ordering.api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ConnectionStrings__Database=Server=orderdb,1433; Database=OrderDb; User Id=sa; Password=Password@123; Encrypt=False; Trust Server Certificate=True
  #     - ConnectionStrings__Redis=distributedcache:6379
  #     - GrpcSettings__CatalogUrl=https://catalog.api:8081
  #     - FeatureManagement__OrderFullfilment=false
  #     - MessageBroker__Host=amqp://messagebroker:5672
  #     - MessageBroker__UserName=guest
  #     - MessageBroker__Password=guest
  #     - Keycloak__BaseUrl=http://keycloak.identity:8080
  #     - Keycloak__Realm=eshop
  #     - Keycloak__ClientId=ordering-service
  #     - Keycloak__ClientSecret=DaUNH3CoWzXmuZkPMAZ4IOpiUGZ84TW0
  #     - Keycloak__GrantType=client_credentials      
  #     - Authentication__Authority=http://keycloak.identity:8080/realms/eshop
  #     - Authentication__ValidIssuer=http://localhost:8080/realms/eshop
  #     - Authentication__ClientId=eshop-client
  #     - Authentication__Audience=account
  #     - Kestrel__Endpoints__Http__Url=http://*:8080
  #     - Kestrel__Endpoints__Https__Url=https://*:8081
  #     - Kestrel__Endpoints__Https__Certificate__Path=/home/app/.aspnet/https/aspnetapp.pfx
  #     - Kestrel__Endpoints__Https__Certificate__Password=david
  #   depends_on:
  #     - keycloak.identity
  #     - catalog.api
  #     - messagebroker
  #     - distributedcache
  #     - orderdb
  #   ports:
  #     - 6003:8080
  #     - 6063:8081
  #   volumes:
  #     - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
  #     # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  yarpapigateway:
    environment:
      <<: *dotnet-common-env
      ASPNETCORE_ENVIRONMENT: Docker
      Authentication__Authority: http://keycloak.identity:8080/realms/eshop
      Authentication__ValidIssuer: http://localhost:8080/realms/eshop
      Authentication__ClientId: eshop-client
      Authentication__Audience: eshop-client
    depends_on:
      - catalog.api
    #   - basket.api
    #   - ordering.api
    ports:
      - 6004:8080
      - 6064:8081
    volumes: *dotnet-common-volumes

  # shopping.web:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ApiSettings__GatewayAddress=http://yarpapigateway:8080

  #     - Kestrel__Endpoints__Http__Url=http://*:8080
  #     - Kestrel__Endpoints__Https__Url=https://*:8081
  #     - Kestrel__Endpoints__Https__Certificate__Path=/home/app/.aspnet/https/aspnetapp.pfx
  #     - Kestrel__Endpoints__Https__Certificate__Password=david
  #   depends_on:
  #     - yarpapigateway
  #   ports:
  #     - "6005:8080"
  #     - "6065:8081"
  #   volumes:
  #     - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
  #     # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro