{{- if .Values.security.istio.enabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-keycloak
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak-svc
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/catalog-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/discount-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-catalog
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: catalog-api
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa
    to:
    - operation:
        ports: ["8081"]
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-basket
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: basket-api
  action: ALLOW
  rules:
  - from:
    - source: 
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"] 
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-discount
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: discount-grpc
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
    to:
    - operation:
        ports: ["8081"]
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-order
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: ordering-api
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-yarp
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: yarp-api-gateway
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/eshop-gateway-istio"]
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-webclient
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: web-client
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/eshop-gateway-istio"]
    to:
    - operation:
        ports: ["8080"]
{{- end }}
