{{- if .Values.security.istio.enabled }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-catalog-to-catalogdb
  namespace: {{ $.Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ $.Values.global.namespace }}/sa/catalog-sa"]
    to:
    - operation:
        hosts: ["{{ .Values.aws.rds.host }}"]
        ports: ["5432"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-basket-to-basketdb
  namespace: {{ $.Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa"]
    to:
    - operation:
        hosts: ["{{ .Values.aws.rds.host }}"]
        ports: ["5432"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ordering-to-orderdb
  namespace: {{ $.Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa"]
    to:
    - operation:
        hosts: ["{{ .Values.aws.rds.host }}"]
        ports: ["1433"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-keycloak-to-keycloakdb
  namespace: {{ $.Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ $.Values.global.namespace }}/sa/keycloak-sa"]
    to:
    - operation:
        hosts: ["{{ .Values.aws.rds.host }}"]
        ports: ["5432"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-cache
  namespace: {{ $.Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa
    to:
    - operation:
        hosts: ["{{ .Values.aws.valkey.host }}"]
        ports: ["6379"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-messagequeue
  namespace: {{ $.Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/catalog-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/keycloak-sa
    to:
    - operation:
        hosts: ["{{ .Values.aws.amazonmq.host }}"]
        ports: ["5671","5672"]
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/eshop-gateway-istio"]
    to:
    - operation:
        hosts: ["{{ .Values.aws.amazonmq.host }}"]
        ports: ["15672"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-keycloak
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak-svc
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/catalog-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/discount-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-catalog
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: catalog-api
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/order-sa
    to:
    - operation:
        ports: ["8081"]
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-basket
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: basket-api
  action: ALLOW
  rules:
  - from:
    - source: 
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"] 
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-discount
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: discount-grpc
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/basket-sa
    to:
    - operation:
        ports: ["8081"]
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-services-to-order
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: ordering-api
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ $.Values.global.namespace }}/sa/yarp-sa
        - cluster.local/ns/istio-system/sa/eshop-gateway-istio
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-yarp
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: yarp-api-gateway
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/eshop-gateway-istio"]
    to:
    - operation:
        ports: ["8080"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-webclient
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: web-client
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/eshop-gateway-istio"]
    to:
    - operation:
        ports: ["8080"]
{{- end }}