{{- range .Values.apps }}
{{- if .config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  namespace: {{ $.Values.global.namespace }}
data:
  {{- range $key, $value := .config }}
{{- $firstPass := tpl (toString $value) $ }}
  {{ $key }}: {{ tpl $firstPass $ | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yarp-config
  namespace: {{ $.Values.global.namespace }}
data:
  appsettings.Production.json: |
    {
      "ReverseProxy": {
        "Routes": {
          "catalog-route": {
            "ClusterId": "catalog-cluster",
            "Match": {
              "Path": "/catalog-service/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          },
          "basket-route": {
            "ClusterId": "basket-cluster",
            "Match": {
              "Path": "/basket-service/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          },
          "discount-route": {
            "ClusterId": "discount-cluster",
            "Match": {
              "Path": "/discount-service/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          },
          "ordering-route": {
            "ClusterId": "ordering-cluster",
            "RateLimiterPolicy": "fixed",
            "Match": {
              "Path": "/ordering-service/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          }
        },
        "Clusters": {
          "catalog-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://catalog-clusterip"
              }
            }
          },
          "basket-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://basket-clusterip"
              }
            }
          },
          "discount-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://discount-clusterip"
              }
            }
          },
          "ordering-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://ordering-clusterip"
              }
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ $.Values.global.namespace }}
data:
  realm-export.json: |
    [
      {
        "realm": "eshop",
        "enabled": true,
        "registrationAllowed": true,
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "resetPasswordAllowed": true,
        "verifyEmail": false,
        "clients": [
          {
            "clientId": "reactApp",
            "protocol": "openid-connect",
            "publicClient": true,
            "redirectUris": [
              "https://{{ tpl .Values.security.istio.hosts.hostApp $ }}/*"
            ],
            "webOrigins": [
              "https://{{ tpl .Values.security.istio.hosts.hostApp $ }}"
            ],
            "attributes": {
              "pkce.code.challenge.method": "S256"
            },
            "protocolMappers": [
              {
                "name": "audience mapper",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-audience-mapper",
                "consentRequired": false,
                "config": {
                  "included.client.audience": "reactApp",
                  "id.token.claim": "true",
                  "access.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "ordering-service",
            "protocol": "openid-connect",
            "publicClient": false,
            "clientAuthenticatorType": "client-secret",
            "secret": "CHANGE_ME",
            "standardFlowEnabled": false,
            "implicitFlowEnabled": false,
            "directAccessGrantsEnabled": false,
            "serviceAccountsEnabled": true,
            "redirectUris": [],
            "webOrigins": [],
            "attributes": {
              "client_credentials.use_refresh_token": "false"
            },
            "protocolMappers": [
              {
                "name": "audience mapper",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-audience-mapper",
                "consentRequired": false,
                "config": {
                  "included.client.audience": "account",
                  "id.token.claim": "true",
                  "access.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "kiali",
            "protocol": "openid-connect",
            "publicClient": true,
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": false,
            "redirectUris": [
              "https://{{ tpl .Values.security.istio.hosts.hostKiali $ }}/*"
            ],
            "webOrigins": [
              "https://{{ tpl .Values.security.istio.hosts.hostKiali $ }}"
            ],
            "attributes": {
              "pkce.code.challenge.method": "S256"
            },
            "protocolMappers": [
              {
                "name": "audience mapper",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-audience-mapper",
                "consentRequired": false,
                "config": {
                  "included.client.audience": "kiali",
                  "id.token.claim": "true",
                  "access.token.claim": "true"
                }
              },
              {
                "name": "realm roles to groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-usermodel-realm-role-mapper",
                "consentRequired": false,
                "config": {
                  "multivalued": "true",
                  "user.attribute": "foo",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "jsonType.label": "String"
                }
              }
            ]
          }
        ],
        "roles": {
          "realm": [
            { "name": "Admin" },
            { "name": "Employee" },
            { "name": "Customer" }
          ]
        },
        "defaultRoles": [ "Customer" ],
        "users": [
          {
            "username": "admin",
            "enabled": true,
            "emailVerified": true,
            "email": "admin@eshop.com",
            "firstName": "Demo",
            "lastName": "Admin",
            "credentials": [{ "type": "password", "value": "admin123", "temporary": false }],
            "realmRoles": [ "Admin", "Customer" ]
          },
          {
            "username": "user",
            "enabled": true,
            "emailVerified": true,
            "email": "user@eshop.com",
            "firstName": "Demo",
            "lastName": "User",
            "credentials": [{ "type": "password", "value": "user123", "temporary": false }],
            "realmRoles": [ "Customer" ]
          },
          {
            "username": "service-account-ordering-service",
            "enabled": true,
            "emailVerified": false,
            "firstName": "",
            "lastName": "",
            "email": "",
            "serviceAccountClientId": "ordering-service",
            "clientRoles": {
              "realm-management": [
                "view-users"
              ]
            }
          }
        ]
      }
    ]
    