{{- range .Values.services }}
{{- $serviceName := .name }}
{{- $grpcPort := 0 }}
{{- range .ports }}
  {{- if or (eq .name "grpc") (eq .appProtocol "grpc") }}
    {{- $grpcPort = .port }}
  {{- end }}
{{- end }}

{{- if $grpcPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $serviceName }}-grpc-route
  namespace: {{ $.Values.global.namespace }}
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: {{ $serviceName }}
    namespace: {{ $.Values.global.namespace }}
  - group: gateway.networking.k8s.io
    kind: Mesh
    name: mesh
    namespace: istio-system
  rules:
  {{- if eq (default "" .strategyType) "canary" }}
  - matches:
    - headers:
      - name: x-version
        value: canary
    backendRefs:
    - name: {{ $serviceName }}-canary
      port: {{ $grpcPort }}
  - backendRefs:
    - name: {{ $serviceName }}
      port: {{ $grpcPort }}
      weight: 100
    - name: {{ $serviceName }}-canary
      port: {{ $grpcPort }}
      weight: 0
  {{- else }}
  - backendRefs:
    - name: {{ $serviceName }}
      port: {{ $grpcPort }}
  {{- end }}
{{- end }}
{{- end }}
