{{- range .Values.apps }}
{{- range .volumes }}
{{- if eq .type "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
  namespace: {{ $.Values.global.namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
{{- end }}
{{- end }}
{{- end }}