apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-sa
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basket-sa
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discount-sa
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-sa
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-sa
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yarp-sa
  namespace: {{ $.Values.global.namespace }}