{{- range .Values.apps }}
{{- if or (ne (default "" .type) "infra") $.Values.global.deployInfrastructure }}

{{- if and .secrets (not .externalSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  namespace: {{ $.Values.global.namespace }}
type: Opaque
data:
{{- range $key, $val := .secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
---
{{- else if .externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-external-secret
  namespace: {{ $.Values.global.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |
            {{- if .externalSecrets.hasDatabase }}
            ConnectionStrings__Database: "Server={{"{{ .db_host }}"}};Port=5432;Database={{"{{ .db_name }}"}};User Id={{"{{ .db_username }}"}};Password={{"{{ .db_password }}"}};Include Error Detail=true"
            {{- end }}

            {{- if .externalSecrets.hasRabbitMQ }}
            MessageBroker__Host: "amqps://{{"{{ .mq_host }}"}}:5671"
            MessageBroker__UserName: "{{"{{ .mq_username }}"}}"
            MessageBroker__Password: "{{"{{ .mq_password }}"}}"
            {{- end }}

            {{- if .externalSecrets.hasRedis }}
            ConnectionStrings__Redis: "{{"{{ .redis_host }}"}},password={{"{{ .redis_password }}"}},user={{"{{ .redis_user }}"}},ssl=true,abortConnect=false"
            RedisInstanceName: "{{"{{ .redis_instance }}"}}"
            {{- end }}
            
            {{- if .externalSecrets.hasAuth }}
            Authentication__ClientId: "{{"{{ .auth_client_id }}"}}"
            Authentication__Audience: "{{"{{ .auth_audience }}"}}"
            KEYCLOAK_CLIENTID: "{{"{{ .auth_client_id }}"}}"
            {{- end }}

            {{- if .externalSecrets.hasKCAuth }}
            Keycloak__ClientId: "{{"{{ .kc_client_id }}"}}"
            Keycloak__ClientSecret: "{{"{{ .kc_client_secret }}"}}"
            {{- end }}

            {{- if .externalSecrets.hasKeycloakAdmin }}
            KC_BOOTSTRAP_ADMIN_USERNAME: "{{"{{ .username }}"}}"
            KC_BOOTSTRAP_ADMIN_PASSWORD: "{{"{{ .password }}"}}"
            {{- end }}

            {{- if .externalSecrets.hasKeycloakDb }}
            KC_DB_URL: "jdbc:postgresql://{{"{{ .db_host }}"}}:5432/{{"{{ .db_name }}"}}"
            KC_DB_USERNAME: "{{"{{ .db_username }}"}}"
            KC_DB_PASSWORD: "{{"{{ .db_password }}"}}"
            {{- end }}
  dataFrom:
  {{- if or .externalSecrets.hasDatabase .externalSecrets.hasKeycloakDb }}
  - extract:
      key: "{{ $.Values.global.projectName }}/{{ $.Values.global.environment }}/db/{{ .name }}"
  {{- end }}
  {{- if .externalSecrets.hasRabbitMQ }}
  - extract:
      key: "{{ $.Values.global.projectName }}/{{ $.Values.global.environment }}/mq/{{ .name }}"
  {{- end }}
  {{- if .externalSecrets.hasRedis }}
  - extract:
      key: "{{ $.Values.global.projectName }}/{{ $.Values.global.environment }}/cache/{{ .name }}"
  {{- end }}
  {{- if or .externalSecrets.hasAuth .externalSecrets.hasKCAuth .externalSecrets.hasKeycloakAdmin }}
  - extract:
      key: "{{ $.Values.global.projectName }}/{{ $.Values.global.environment }}/auth/{{ .name }}"
  {{- end }}

---
{{- end }}
{{- end }}
{{- end }}