{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .selector }}
  type: {{ default "ClusterIP" .type }}
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .protocol }}
      protocol: {{ .protocol }}
      {{- end }}
    {{- end }}

{{- if hasKey . "strategyType" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ if eq .strategyType "blueGreen" }}preview{{ else }}canary{{ end }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .selector }}
  type: {{ default "ClusterIP" .type }}
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .protocol }}
      protocol: {{ .protocol }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}