{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .selector }}
  type: {{ .type }}
  ports:
    {{- toYaml .ports | nindent 4 }}
{{- if eq .strategyType "blueGreen" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-preview
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ .selector }}
  type: {{ .type }}
  ports:
    {{- toYaml .ports | nindent 4 }}
{{- end }}
{{- end }}