{{- range .Values.services }}
{{- if eq .strategyType "canary" }}
{{- $svcName := .name }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .selector }}-vs
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
    - {{ $svcName }}.{{ $.Values.global.namespace }}.svc.cluster.local
  gateways:
    - mesh
  http:
  {{- range .ports }}
    {{- if eq .name "http" }}
    - name: http-route
      match:
        - port: {{ .port }}
      route:
        - destination:
            host: {{ $svcName }}.{{ $.Values.global.namespace }}.svc.cluster.local
            subset: stable
          weight: 100
        - destination:
            host: {{ $svcName }}.{{ $.Values.global.namespace }}.svc.cluster.local
            subset: canary
          weight: 0
    {{- else if eq .name "grpc" }}
    - name: grpc-route
      match:
        - port: {{ .port }}
      route:
        - destination:
            host: {{ $svcName }}.{{ $.Values.global.namespace }}.svc.cluster.local
            subset: stable
          weight: 100
        - destination:
            host: {{ $svcName }}.{{ $.Values.global.namespace }}.svc.cluster.local
            subset: canary
          weight: 0
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: eshop-app-vs
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
    - {{ .Values.security.istio.hosts.hostApp }}
  gateways:
    - eshop-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: web-client-clusterip.{{ $.Values.global.namespace }}.svc.cluster.local
            port:
              number: 80
      timeout: 5s
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: eshop-api-vs
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
    - {{ .Values.security.istio.hosts.hostApi }}
  gateways:
    - eshop-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: yarp-api-gateway-clusterip.{{ $.Values.global.namespace }}.svc.cluster.local
            port:
              number: 80
      timeout: 5s
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: eshop-id-vs
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
    - {{ .Values.security.istio.hosts.hostId }}
  gateways:
    - eshop-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: keycloak-clusterip.{{ $.Values.global.namespace }}.svc.cluster.local
            port:
              number: 8080
      timeout: 5s