datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
        jsonData:
          derivedFields:
            - name: TraceID
              datasourceUid: tempo
              matcherRegex: "trace_id=(\\w+)"
              url: "$${__value.raw}"
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo-distributed-query-frontend.monitoring.svc.cluster.local:3200
        access: proxy
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: 'loki'
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            tags: [{ key: 'service.name', value: 'service_name' }]
      - name: Mimir
        type: prometheus
        uid: mimir
        url: http://mimir-distributed-query-frontend.monitoring.svc.cluster.local:8080/prometheus
        access: proxy
        isDefault: false
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'anonymous'
