global:
  extraEnvFrom: []
  clusterDomain: cluster.local
storage:
  trace:
    backend: s3
    s3:
      bucket: eshop-dev-tempo-storage-tgxj
      region: us-east-1
      endpoint: s3.us-east-1.amazonaws.com
      forcepathstyle: false
tempo:
  extraArgs:
    config.expand-env: "true"
  structuredConfig:
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - tempo-distributed-gossip-ring.monitoring.svc.cluster.local
serviceAccount:
  create: true
  name: tempo
traces:
  otlp:
    grpc:
      enabled: true
      port: 4317
    http:
      enabled: true
ingester:
  replicas: 1
  config:
    replication_factor: 1
    max_block_duration: 5m 
    complete_block_timeout: 1m

gateway:
  enabled: true
querier:
  replicas: 1
queryFrontend:
  replicas: 1
distributor:
  replicas: 1
compactor:
  replicas: 1
