apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-rollouts-gateway-api-plugin-final
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "httproutes/status", "httproutes/finalizers", "gateways"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-rollouts-gateway-api-plugin-final-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollouts-gateway-api-plugin-final
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts
