global:
  namespace: eshop-dev
  projectName: eshop
  environment: dev
  ns: false
  domain: davidlihor.com
  monitoring: true
security:
  issuer:
    email: davidlihor@gmail.com
aws:
  region: us-east-1
  rds:
    host: "*"
  valkey:
    host: "*"
  amazonmq:
    host: "*"
