global:
  istioInjection: true
  deployInfrastructure: false
  namespace: eshop
  projectName: eshop
  environment: dev
  ns: true
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 5
  terminationGracePeriodSeconds: 20
defaultResources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"
aws:
  region: us-east-1
  rds:
    host: "*"
    port: 5432
  valkey:
    host: "*"
    port: 6379
  amazonmq:
    host: "*"
    ports:
      amqp: 5672
      amqps: 5671
      management: 15672
security:
  istio:
    enabled: true
    mtlsMode: STRICT
    tlsSecret: eshop-tls
    hosts:
      hostApp: app.eshop.local
      hostApi: api.eshop.local
      hostId: id.eshop.local

services:
  - name: catalogdb-svc
    selector: catalog-db
    ports:
    - name: tcp
      port: 5432

  - name: basketdb-svc
    selector: basket-db
    ports:
    - name: tcp
      port: 5432

  - name: orderdb-svc
    selector: order-db
    ports:
    - name: tcp
      port: 1433
      targetPort: 1433

  - name: keycloak-db-svc
    selector: keycloak-db
    ports:
    - name: tcp
      port: 5432

  - name: redis-svc
    selector: redis
    ports:
    - name: tcp
      port: 6379

  - name: rabbitmq-svc
    selector: rabbit-mq
    ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672

  - name: keycloak-clusterip
    selector: keycloak-svc
    ports:
    - name: http
      port: 8080

  - name: catalog-clusterip
    strategyType: canary
    selector: catalog-api
    ports:
    - name: http
      protocol: http  
      port: 80
      targetPort: 8080   
    - name: grpc
      protocol: grpc 
      port: 8081
      targetPort: 8081

  - name: basket-clusterip
    strategyType: blueGreen
    selector: basket-api
    ports:
    - name: http
      port: 80
      targetPort: 8080

  - name: discount-clusterip
    selector: discount-grpc
    ports:
    - name: http
      protocol: http
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: grpc 
      port: 8080
      targetPort: 8081

  - name: ordering-clusterip
    selector: ordering-api
    ports:
    - name: http
      port: 80
      targetPort: 8080

  - name: yarp-api-gateway-clusterip
    selector: yarp-api-gateway
    ports:
    - name: http
      port: 80
      targetPort: 8080

  - name: web-client-clusterip
    selector: web-client
    ports:
    - name: http
      port: 80
      targetPort: 8080

apps:
  - name: catalog-db
    type: infra
    image:
      repository: postgres
      tag: latest
    labels: 
      app: catalog-db
      proj: eshop
    replicaCount: 1
    revisionHistoryLimit: 2
    ports: 
      - port: 5432
    externalSecrets:
      secretStoreName: aws-secrets-backend
    volumes:
      - name: catalog-volume
        mountPath: /postgres-data
        type: pvc

  - name: basket-db
    type: infra
    image:
      repository: postgres
      tag: latest
    labels: 
      app: basket-db
      proj: eshop
    replicaCount: 1
    revisionHistoryLimit: 2
    ports:
      - port: 5432
    externalSecrets:
      secretStoreName: aws-secrets-backend
    volumes:
      - name: basket-volume
        mountPath: /postgres-data
        type: pvc

  - name: order-db
    type: infra
    image:
      repository: postgres
      tag: latest
    labels: 
      app: order-db
      proj: eshop
    replicaCount: 1
    revisionHistoryLimit: 2
    ports:
      - port: 5432
    externalSecrets:
      secretStoreName: aws-secrets-backend
    volumes:
      - name: order-volume
        mountPath: /postgres-data
        type: pvc

  - name: keycloak-db
    type: infra
    image:
      repository: postgres
      tag: latest
    labels: 
      app: keycloak-db
      proj: eshop
    replicaCount: 1
    ports:
      - port: 5432
    externalSecrets:
      secretStoreName: aws-secrets-backend
    volumes:
      - name: keycloak-volume
        mountPath: /postgres-data
        type: pvc

  - name: redis
    type: infra
    image:
      repository: redis
      tag: latest
    labels: 
      app: redis
      proj: eshop
    replicaCount: 1
    ports:
      - port: 6379

  - name: rabbit-mq
    type: infra
    image:
      repository: rabbitmq
      tag: 3-management
    labels: 
      app: rabbit-mq
      proj: eshop
    replicaCount: 1
    ports: 
      - port: 5672
      - port: 15672
    externalSecrets:
      secretStoreName: aws-secrets-backend

  - name: keycloak-svc
    image:
      repository: quay.io/keycloak/keycloak
      tag: latest
    labels: 
      app: keycloak-svc
      proj: eshop
    replicaCount: 1
    sa: keycloak-sa
    args:
      - start-dev
      - --import-realm
    ports:
      - port: 8080
    config:
      KC_DB: postgres
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: keycloak.exchange
      KC_PROXY: edge
      KC_HOSTNAME: "https://{{ .Values.security.istio.hosts.hostId }}"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
    externalSecrets:
      hasKeycloakDb: true
      secretStoreName: aws-secrets-backend
    volumes:
      - name: keycloak-config
        mountPath: /opt/keycloak/data/import/realm-export.json
        subPath: realm-export.json
        type: configMap

  - name: catalog-api
    image:
      repository: davidlihor/catalogapi
      tag: latest
    labels: 
      app: catalog-api
      proj: eshop
    replicaCount: 1
    sa: catalog-sa
    ports: 
      - port: 8080
        name: http
      - port: 8081
        name: grpc
    config:
      ASPNETCORE_ENVIRONMENT: Development
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Kestrel__Endpoints__WebApi__Url: http://+:8080
      Kestrel__Endpoints__WebApi__Protocols: Http1
      Kestrel__Endpoints__Grpc__Url: http://+:8081
      Kestrel__Endpoints__Grpc__Protocols: Http2
      Observability__OtlpEndpoint: http://alloy.monitoring.svc.cluster.local:4317
    externalSecrets:
      hasDatabase: true
      hasRabbitMQ: true
      hasAuth: true
      secretStoreName: aws-secrets-backend
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080

  - name: basket-api
    image:
      repository: davidlihor/basketapi
      tag: latest
    labels:
      app: basket-api
      proj: eshop
    replicaCount: 1
    sa: basket-sa
    svc: basket-clusterip
    ports:
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Development
      GrpcSettings__CatalogUrl: http://catalog-clusterip:8081
      GrpcSettings__DiscountUrl: http://discount-clusterip:8080
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Observability__OtlpEndpoint: http://alloy.monitoring.svc.cluster.local:4317
    externalSecrets:
      hasDatabase: true
      hasRabbitMQ: true
      hasRedis: true
      hasAuth: true
      secretStoreName: aws-secrets-backend
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080

  - name: discount-grpc
    image:
      repository: davidlihor/discountgrpc
      tag: latest
    labels: 
      app: discount-grpc
      proj: eshop
    replicaCount: 1
    sa: discount-sa
    ports:
      - port: 8080
      - port: 8081
    config:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Data Source=discountdb.db
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Kestrel__Endpoints__WebApi__Url: http://+:8080
      Kestrel__Endpoints__WebApi__Protocols: Http1
      Kestrel__Endpoints__Grpc__Url: http://+:8081
      Kestrel__Endpoints__Grpc__Protocols: Http2
      Observability__OtlpEndpoint: http://alloy.monitoring.svc.cluster.local:4317
    externalSecrets:
      hasAuth: true
      secretStoreName: aws-secrets-backend
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080

  - name: ordering-api
    image:
      repository: davidlihor/orderingapi
      tag: latest
    labels:
      app: ordering-api
      proj: eshop
    replicaCount: 1
    sa: order-sa
    ports:
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Development
      GrpcSettings__CatalogUrl: http://catalog-clusterip:8080
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Keycloak__BaseUrl: http://keycloak-clusterip:8080
      Keycloak__Realm: eshop
      Keycloak__GrantType: client_credentials
      FeatureManagement__OrderFullfilment: "false"
      Observability__OtlpEndpoint: http://alloy.monitoring.svc.cluster.local:4317
    externalSecrets:
      hasDatabase: true
      hasRabbitMQ: true
      hasRedis: true
      hasAuth: true
      hasKCAuth: true
      secretStoreName: aws-secrets-backend
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080

  - name: yarp-api-gateway
    image:
      repository: davidlihor/yarpapigateway
      tag: latest
    imagePullPolicy: Always
    labels: 
      app: yarp-api-gateway
      proj: eshop
    replicaCount: 1
    sa: yarp-sa
    ports:
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Production
      ALLOWED_ORIGINS: "https://{{ .Values.security.istio.hosts.hostApp }}"
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Observability__OtlpEndpoint: http://alloy.monitoring.svc.cluster.local:4317
    externalSecrets:
      hasAuth: true
      secretStoreName: aws-secrets-backend
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080
    volumes:
      - name: yarp-config
        mountPath: /app/appsettings.Production.json
        subPath: appsettings.Production.json
        type: configMap

  - name: web-client
    image:
      repository: davidlihor/shoppingweb
      tag: latest
    labels: 
      app: web-client
      proj: eshop
    replicaCount: 1
    ports:
      - port: 8080
    config:
      YARP_API_URL: "https://{{ .Values.security.istio.hosts.hostApi }}"
      KEYCLOAK_URL: "https://{{ .Values.security.istio.hosts.hostId }}"
      KEYCLOAK_REALM: eshop
    externalSecrets:
      hasAuth: true
      secretStoreName: aws-secrets-backend
