global:
  istioInjection: true
  namespace: eshop
  environment: dev
  ns: true
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 5
  terminationGracePeriodSeconds: 20
defaultResources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"
prometheus:
  enabled: false
  namespaceSelector:
    matchNames:
      - default
      - eshop
security:
  istio:
    enabled: true
    mtlsMode: STRICT
    tlsSecret: eshop-tls
    hosts:
      hostApp: app.eshop.local
      hostApi: api.eshop.local
      hostId: id.eshop.local

services:
  - name: catalogdb-svc
    selector: catalog-db
    type: ClusterIP
    ports:
    - name: tcp
      port: 5432

  - name: basketdb-svc
    selector: basket-db
    type: ClusterIP
    ports:
    - name: tcp
      port: 5432

  - name: orderdb-svc
    selector: order-db
    type: ClusterIP
    ports:
    - name: tcp
      port: 1433
      targetPort: 1433

  - name: keycloak-db-svc
    selector: keycloak-db
    type: ClusterIP
    ports:
    - name: tcp
      port: 5432

  - name: redis-svc
    selector: redis
    type: ClusterIP
    ports:
    - name: tcp
      port: 6379

  - name: rabbitmq-svc
    selector: rabbit-mq
    type: ClusterIP
    ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672

  - name: seq-svc
    selector: discount-seq
    type: ClusterIP
    ports:
    - name: ingest
      port: 5341
    - name: http
      port: 80

  - name: keycloak-clusterip
    selector: keycloak-svc
    type: ClusterIP
    ports:
    - name: http
      port: 8080

  - name: catalog-clusterip
    strategyType: canary
    selector: catalog-api
    type: ClusterIP
    ports:
    - name: http
      port: 80
    - name: grpc
      port: 8080

  - name: basket-clusterip
    strategyType: blueGreen
    selector: basket-api
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 8080

  - name: discount-clusterip
    selector: discount-grpc
    type: ClusterIP
    ports:
    - name: http
      port: 80
    - name: grpc
      port: 8080

  - name: ordering-clusterip
    selector: ordering-api
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 8080

  - name: yarp-api-gateway-clusterip
    selector: yarp-api-gateway
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 8080

  - name: web-client-clusterip
    selector: web-client
    type: ClusterIP
    ports:
    - name: http
      port: 80

apps:
  - name: catalog-db
    image:
      repository: postgres
      tag: latest
    labels: 
      app: catalog-db
      proj: eshop
    replicaCount: 1
    revisionHistoryLimit: 2
    ports: 
      - port: 5432
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/catalog-db"
    volumes:
      - name: catalog-volume
        mountPath: /postgres-data
        type: pvc

  - name: basket-db
    image:
      repository: postgres
      tag: latest
    labels: 
      app: basket-db
      proj: eshop
    replicaCount: 1
    revisionHistoryLimit: 2
    ports:
      - port: 5432
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/basket-db"
    volumes:
      - name: basket-volume
        mountPath: /postgres-data
        type: pvc

  - name: order-db
    image:
      repository: mcr.microsoft.com/mssql/server
      tag: 2022-latest
    labels: 
      app: order-db
      proj: eshop
    replicaCount: 1
    revisionHistoryLimit: 2
    ports:
      - port: 1433
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/order-db"
    volumes:
      - name: mssql-conf
        mountPath: /var/opt/mssql/mssql.conf
        subPath: mssql.conf
        type: configMap
      - name: order-volume
        mountPath: /var/opt/mssql/userdata
        type: pvc

  - name: keycloak-db
    image:
      repository: postgres
      tag: latest
    labels: 
      app: keycloak-db
      proj: eshop
    replicaCount: 1
    ports:
      - port: 5432
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/keycloak-db"
    volumes:
      - name: keycloak-volume
        mountPath: /postgres-data
        type: pvc

  - name: redis
    image:
      repository: redis
      tag: latest
    labels: 
      app: redis
      proj: eshop
    replicaCount: 1
    ports:
      - port: 6379

  - name: rabbit-mq
    image:
      repository: rabbitmq
      tag: 3-management
    labels: 
      app: rabbit-mq
      proj: eshop
    replicaCount: 1
    ports: 
      - port: 5672
      - port: 15672
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/rabbit-mq"

  - name: discount-seq
    image:
      repository: datalust/seq
      tag: latest
    labels: 
      app: discount-seq
      proj: eshop
    replicaCount: 1
    ports:
      - port: 5341
      - port: 80
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/discount-seq"
    volumes:
      - name: seq-data
        mountPath: /data
        type: pvc

  - name: keycloak-svc
    image:
      repository: quay.io/keycloak/keycloak
      tag: latest
    labels: 
      app: keycloak-svc
      proj: eshop
    replicaCount: 1
    sa: keycloak-sa
    args:
      - start-dev
      - --import-realm
    ports:
      - port: 8080
    config:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db-svc
      KC_DB_URL_PORT: 5432
      KK_TO_RMQ_URL: rabbitmq-svc
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: keycloak.exchange
      KC_PROXY: edge
      KC_HOSTNAME: "https://{{ .Values.security.istio.hosts.hostId }}"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/keycloak-svc"
    volumes:
      - name: keycloak-config
        mountPath: /opt/keycloak/data/import/realm-export.json
        subPath: realm-export.json
        type: configMap

  - name: catalog-api
    image:
      repository: catalogapi
      tag: latest
    labels: 
      app: catalog-api
      proj: eshop
    replicaCount: 1
    sa: catalog-sa
    ports: 
      - port: 80
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Development
      MessageBroker__Host: amqp://rabbitmq-svc:5672
      MessageBroker__UserName: guest
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Kestrel__Endpoints__WebApi__Url: http://+:80
      Kestrel__Endpoints__WebApi__Protocols: Http1
      Kestrel__Endpoints__Grpc__Url: http://+:8080
      Kestrel__Endpoints__Grpc__Protocols: Http2
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/catalog-api"
    readinessProbe:
    livenessProbe:

  - name: basket-api
    image:
      repository: basketapi
      tag: latest
    labels:
      app: basket-api
      proj: eshop
    replicaCount: 1
    sa: basket-sa
    svc: basket-clusterip
    ports:
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Redis: redis-svc:6379
      MessageBroker__Host: amqp://rabbitmq-svc:5672
      MessageBroker__UserName: guest
      GrpcSettings__CatalogUrl: http://catalog-clusterip:8080
      GrpcSettings__DiscountUrl: http://discount-clusterip:8080
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/basket-api"
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080

  - name: discount-grpc
    image:
      repository: discountgrpc
      tag: latest
    labels: 
      app: discount-grpc
      proj: eshop
    replicaCount: 1
    sa: discount-sa
    ports:
      - port: 80
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Data Source=discountdb.db
      OTEL_EXPORTER_OTLP_ENDPOINT: HTTP://seq-svc:5341/ingest/otlp/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      Seq__ServerUrl: http://seq-svc:5341
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
      Kestrel__Endpoints__WebApi__Url: http://+:80
      Kestrel__Endpoints__WebApi__Protocols: Http1
      Kestrel__Endpoints__Grpc__Url: http://+:8080
      Kestrel__Endpoints__Grpc__Protocols: Http2
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/discount-grpc"
    readinessProbe:
    livenessProbe:

  - name: ordering-api
    image:
      repository: orderingapi
      tag: latest
    labels:
      app: ordering-api
      proj: eshop
    replicaCount: 1
    sa: order-sa
    ports:
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Redis: redis-svc:6379
      MessageBroker__Host: amqp://rabbitmq-svc:5672
      MessageBroker__UserName: guest
      GrpcSettings__CatalogUrl: http://catalog-clusterip:8080
      Keycloak__BaseUrl: http://keycloak-clusterip:8080
      Keycloak__Realm: eshop
      Keycloak__GrantType: client_credentials      
      FeatureManagement__OrderFullfilment: "false"
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/ordering-api"
    readinessProbe:
      port: 8080
    livenessProbe:
      port: 8080

  - name: yarp-api-gateway
    image:
      repository: yarpapigateway
      tag: latest
    labels: 
      app: yarp-api-gateway
      proj: eshop
    replicaCount: 1
    sa: yarp-sa
    ports:
      - port: 8080
    config:
      ASPNETCORE_ENVIRONMENT: Production
      ALLOWED_ORIGINS: "https://{{ .Values.security.istio.hosts.hostApp }}"
      Authentication__Authority: http://keycloak-clusterip:8080/realms/eshop
      Authentication__ValidIssuer: "https://{{ .Values.security.istio.hosts.hostId }}/realms/eshop"
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/yarp-gateway"
    volumes:
      - name: yarp-config
        mountPath: /app/appsettings.Production.json
        subPath: appsettings.Production.json
        type: configMap

  - name: web-client
    image:
      repository: shoppingweb
      tag: latest
    labels: 
      app: web-client
      proj: eshop
    replicaCount: 1
    ports:
      - port: 80
    config:
      YARP_API_URL: "https://{{ .Values.security.istio.hosts.hostApi }}"
      KEYCLOAK_URL: "https://{{ .Values.security.istio.hosts.hostId }}"
    externalSecrets:
      enabled: true
      secretStoreName: vault-backend
      remoteRef: "eshop/{{ .Values.global.environment }}/web-client"